mondrian: Add missing camera blob
This fixes grainy images when using night mode in MiuiCamera.

E vendor.qti.camera.provider@2.7-service_64: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:1496: Error 0x80000406: remote_handle64_open failed for file:///libQnnHtpV69Skel.so?qnn_skel_handle_invoke&_modver=1.0&_dom=cdsp (errno Success)

Change-Id: I85822c4b46655c04969d2cd1fe33e99750343f74